### ISSUE TITLE
Can't use the --set-upstream option

### ISSUE THREAD

**Issue by SkxNMDI5** [mateodelnorte/meta-git#13]
Hi,

I use the following command to push and set the origin of a branch :
```sh
meta git push --set-upstream origin 1.3.x
```

But I got the following errors in each of my modules :
```sh
my_module:
fatal: The current branch 1.3.x has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin 1.3.x

my_module exited with error: Error: Command failed: git push 1.3.x --set-upstream origin
```

It looks like my push command has been transformed by meta in a bad way.

Meta version : 1.0.48

Thx

**Comment by nomadeous** [comment]
Found a way to be compatible :

```
meta git push origin --set-upstream 1.3.x
```

**Comment by SkxNMDI5** [comment]
That's Working.

Thx

**Comment by mateodelnorte** [comment]
I think the error message you first saw was correct. That particular repo
did not have an upstream to set to.

**Comment by Jcbobo** [comment]
when you make pull/push git will pront to use ` $ git push --set-upstream origin 1.3.x`  is annoing to not be able to use the git suggestions (both for push and pull commands)

**Comment by mateodelnorte** [comment]
I'm not following here. It's completely normal to have to set a default remote branch on a git repo, after first cloning. This is not particular to `meta-git`. It's particular to `git`. 

https://stackoverflow.com/a/18032014/602377

If you're seeing errors on some branches and not others when doing things like `--set-upstream`, then you probably don't have that remote branch on all those repos. 

After you add a project, you need to cd into the repo and set the remote branch to what you want.

**Comment by Jcbobo** [comment]
The point is not you have to do it but the fixed option order (if you change the option order meta-git fails) 

the annoing part is when you make a git push without setting the upstream git will promt with the command to set it, in that command the option order is not the one specified in the meta-git push validation, so meta-git validation will fail.
Since this aspect is not documented  it appear to be impossible to set the upstream

**Comment by mateodelnorte** [comment]
I think I follow now. So, essentially, the same as #21 ?

**Comment by Jcbobo** [comment]
not exaclty in this case the issue is related to options order in the #21  is related to missing  string ( the only one allowed in validation are git pull [options] [ <repo> [<ref....>] ] a token is missing in the regexp to make the match workiing  (git pull [options] [remote] [branch])

i think the git-meta should rely on git validation instead of re-implementing it  and handle correlcty the results ( probably this should be a good rules for all the plugins)
