### ISSUE TITLE
add support for git alias commands

### ISSUE THREAD

**Issue by gdamoreira** [mateodelnorte/meta-git#18]

**Comment by patrickleet** [comment]
`meta exec "alias"` ?

**Comment by gdamoreira** [comment]
Considering `git st` as an alias to `git status`.
Executing `meta git st` is much better than `meta exec "git st"`.

Don't you agree?

**Comment by mateodelnorte** [comment]
These are aliases in general, not particular to git. Unfortunately, your aliases are determined by your local ~/.bashrc, ~/.bash_profile, ~/.zshrc, etc, file and there's no easy way to assume what shell or profile file someone will be depending on for normal use. Since we use child_process.exec, essentially, to execute these processes, a new shell is being spawned which will not have access to the aliases that would otherwise be set up by these files. 

Happy to field a PR for something that would implement making it work, but it was a bit to bite off last I looked into it.

**Comment by gdamoreira** [comment]
Usually these alias is configured directly from git using `git config --global alias.st status` or `git config alias.st status`.

This configuration uses git config file in `.git/config` or `~/.gitconfig` to save this settings:

The file looks like:
```
...
[alias]
	co = checkout
	st = status
...
```

Maybe using this config file could be possible to extends to use git's aliases, right?

**Comment by mateodelnorte** [comment]
Happy to field a pull request for it.

**Comment by JordanAdams** [comment]
Would it be simpler to just make `meat-git` act as a super thin passthrough for `git`? Essentially `meta git [args]` will just perform `git [args]` across each repo. This would allow for full feature parity with `git` and any aliases the user has set up.

**Comment by mateodelnorte** [comment]
Yes, except that wouldn't give help providing a list of commands or syntax
for each child command.

**Comment by gdamoreira** [comment]
I agree @JordanAdams, for now I created an alias in my shell:
```
function gitm {
    args="$@"
    meta exec "git $args"
}
```
I use my commands like: 
```
gitm st
gitm co branch
```

👍
